spring:
  profiles:
    active:
    - dev
---
spring:
  config:
    activate:
      on-profile:
      - dev
  application:
    name: mldnconfig-test-dev
---
spring:
  config:
    activate:
      on-profile:
      - product
  application:
    name: mldnconfig-test-product
    